language: python
python:
  - "3.5"

before_install:
- git submodule update --init --recursive

install:
   - wget https://mdipierro.pythonanywhere.com/examples/static/web2py_src.zip
   - unzip web2py_src.zip
   - cd web2py
   - cd applications
#   - "git clone https://github.com/Medisur/journalmanagement.git && cd journalmanagement && pip install -r requirements.txt &&  python setup.py develop && cd .. "
   - "git clone https://github.com/Medisur/journalmanagement.git"
#   - pip install -r requirements.txt
#   # Travis builder defaults don't play nicely with multiprocessing.Queue
#   - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
   - cd ..
   - python web2py.py -i localhost --nogui --debug=0 -p 8000 -a 'supersekret' &> web2py.log &
   - sleep 5 # give the webserver time to startup


script: py.test -x -v -s applications/journalmanagement/tests